CREATE TABLE thirst(
	id INTEGER PRIMARY KEY,
	total INTEGER NOT NULL,
	pool INTEGER NOT NULL,
	step INTEGER NOT NULL,
    prevStep INTEGER NOT NULL
);

CREATE TABLE hunger(
	id INTEGER PRIMARY KEY,
	total INTEGER NOT NULL,
	pool INTEGER NOT NULL,
	step INTEGER NOT NULL,
    prevStep INTEGER NOT NULL
);

CREATE TABLE fatigue(
	id INTEGER PRIMARY KEY,
	total INTEGER NOT NULL,
	pool INTEGER NOT NULL,
	step INTEGER NOT NULL,
    prevStep INTEGER NOT NULL
);

DROP TABLE thirst;
DROP TABLE hunger;
DROP TABLE fatigue;